--- #YAML:1.0
name:                Finance-TW-TSEQuote
version:             0.27
abstract:            Check stock quotes from Taiwan Securities Exchange with Perl
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    LWP::Simple:                   0
    URI::Escape:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Chia-liang Kao (clkao@clkao.org)
